# Generated by Django 4.1.2 on 2022-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_book_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(max_length=50, verbose_name='Дата публикации'),
        ),
    ]
